server:
  port: 8082
  servlet:
    context-path: /ecommerce/v1
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: root

services:
  product-service: http://localhost:8080/ecommerce/v1