server:
  port: 8080
  servlet:
    context-path: /ecommerce/v1
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: root
    password: root
